#!/bin/bash
# git-mv-submodules
# (c) Copyright 2013 wkevin <wkevin27@gmail.com>
# Licensed on the terms of the GNU GPL version 3
# Require:
# When I collect many submodules ,it is necessary to move them from 
# one folder to another folder for ordering them.
# Genearaly we put submodules in a independent folder,such as vender whitch parent folder
# such as foo. So, I want to move all submodules in this vender folder 
# from "foo" folder to another path (such as "bar" folder)with same direction tree struction.
# 需求：
# 指定"源目录/文件夹"、"目的目录"
# 根据 .gitmodules 文件，逐个移动"文件夹"中的submodule到"目的目录"中
# 目录树结构不变
# 移动的是"文件夹"，而不是"源目录"

function usage ()
{
	echo -----------------------------------------------------------
	echo "usage: $(basename $0) [-v] [-t] foo/Folder bar/"
	echo "Folder will move from foo to bar"
	echo "[-v] verbose"
	echo "[-t] test: only show whitch submodule will move without real move"
	echo "Attention:"
	echo "1.git-move-submodules file must in same dir with .gitmodules"
	echo "2.bar must exist "
    echo "3.foo can be NONE"
	echo -----------------------------------------------------------
	return
} 

function eo()
{
	$VERBOSE && echo $1
}

VERBOSE=false
TEST=false
for arg in $*; do
if [ $arg = "-v" -o $arg = '--verbose' ]; then
	VERBOSE=true
	shift
fi
if [ $arg = '-t' -o $arg = '--test' ]; then
	TEST=true
	shift
fi
done


# check the number of args
if [ $# -lt 2 ]; then
	usage
	exit 0
fi

# check the availability of source and targe path
if [ ! -d ${1} ]; then
	echo [ERROR] Source path must exist
	usage
	exit 2
fi

if [ ! -d ${2} ]; then
	echo [ERROR] Target path must exist
	usage
	exit 2
fi

# check if in the root direct with .gitmodules
if [ ! -r .gitmodules ]; then
	echo [ERROR] Action this file in folder including .gitmodules 
	usage
	exit 2
fi

# split args
OLDPATH=${1%%/}
FOLDER=${OLDPATH##*/}
OLDPARENT=${OLDPATH%/*}
NEWPARENT=${2%%/}

if [ ! "${OLDPARENT##/*}" = "$OLDPARENT" ]; then
	OLDPARENT_CANONICAL="$OLDPARENT"
else
	OLDPARENT_CANONICAL="$PWD/$OLDPARENT"
fi

if [ ! "${NEWPARENT##/*}" = "$NEWPARENT" ]; then
	NEWPARENT_CANONICAL="$NEWPARENT"
else
	NEWPARENT_CANONICAL="$PWD/$NEWPARENT"
fi

eo "VERBOSE  = $VERBOSE"
eo "TEST  = $TEST"
eo "OLDPATH   = $OLDPATH"
eo "FOLDER = $FOLDER"
eo "OLDPARENT = $OLDPARENT"
eo "NEWPARENT = $NEWPARENT"
eo "OLDPARENT_CANONICAL = $OLDPARENT_CANONICAL"
eo "NEWPARENT_CANONICAL = $NEWPARENT_CANONICAL"
eo "----"

# step1. find the submodules in .gitmodules and $OLDPATH
if [ -f .targetSubmodules ]; then
	eo "Delete .targetSubmodules"
	rm -rf .targetSubmodules
fi
awk '/path \=/ {
	if (1 == index($3, "'"$OLDPATH"'"))
		print $3
}' .gitmodules > .targetSubmodules

cat .targetSubmodules

if [ ! -s .targetSubmodules -o ! -f .targetSubmodules ]; then
	echo "Can not find submodule in $OLDPATH"
	echo exit
	exit 0
fi

# step2. creat new dir tree in $NEWPARENT
while read line  
do
	l=${line%/*}
	ll=$NEWPARENT_CANONICAL/${l/*$FOLDER/$FOLDER}
	eo "mkdir -p $ll"
	mkdir -p $ll
done<.targetSubmodules

# step3. move submodules one by one
while read line  
do
	SRC_PATH=${line%/*}
	DEST_PATH=$NEWPARENT/${SRC_PATH/*$FOLDER/$FOLDER}
	SUBMODULE=${line##*/}

	eo "~~~~~~~~~"
	eo "line = $line"
	eo "SRC_PATH = $SRC_PATH"
	eo "DEST_PATH = $DEST_PATH"
	eo "SUBMODULE = $SUBMODULE"

	echo "git mv $line $DEST_PATH/"
	echo "sed -i 's%^\(.submodule.\).*$line.*%\1\"$DEST_PATH/$SUBMODULE\"]%' .gitmodules"
	if [ $TEST = true ]; then
		continue
	fi

	# step3.1 call git mv, it can 
	# i)    modify path in .gitmodules file, but not name
	# ii)   create submodule new path and copy contents of submodule
	# iii)  modify worktree in .git/modules/xxx/config file if this file exist
	git mv $line $DEST_PATH/
	if [ 0 != $? ]; then
		echo exit
		exit 3
	fi

	# step3.2 modify name in .gitmodules file and add it to index
	sed -i 's%^\(.submodule.\).*'$line'.*%\1"'$DEST_PATH'/'$SUBMODULE'"]%' .gitmodules
	git add .gitmodules

	# step3.3 move .git/modules/xxx and modify gitdir in xxx/.git file 
	#         They are not exist when you havnt git update this submodule
	if [ 1 -eq 2 ]; then
		if [ -d .git/modules/$SRC_PATH ]; then
			mkdir -p .git/modules/$DEST_PATH
			mv .git/modules/$SRC_PATH/$SUBMODULE .git/modules/$DEST_PATH/
			sed -i -e s%\(.*gitdir:.\)\(.*\)%\1''% $DEST_PATH/$SUBMODULE/.git
		fi
	else
		# need not do this
		# the .git/modules/xxx will not disturb your git work
		# and when you git clone a new repo,and then git update -i, all things will be ok
		echo 
	fi
	echo ===========================================
done<.targetSubmodules

